#!/usr/bin/env sh

MDOCDATE=$(date "+%d %m %Y" | sed '
s/ 01/ Janurary/
s/ 02/ February/
s/ 03/ March/
s/ 04/ April/
s/ 05/ May/
s/ 06/ June/
s/ 07/ July/
s/ 08/ August/
s/ 09/ September/
s/ 10/ October/
s/ 11/ November/
s/ 12/ December/
')

git status --porcelain | while IFS= read -r FILE; do
	FIRST="$(echo "$FILE" | cut -c 1)"
	case "$FIRST" in
	' '|D)
		continue
		;;
	*)
		FILE="$(echo "$FILE" | awk '{ print $2 }')"
		case "${FILE##*.}" in
		[1-7])
			sed -i '/^\.Dd/s/.*/.Dd $Mdocdate: '"$MDOCDATE"' $/' "$FILE"
			git add "$FILE"
			;;
		esac
		;;
	esac
done
exit 0
