.Dd $Mdocdate: 30 July 21 $
.Dt PP 1 URM
.Os mutils
.Sh NAME
.Nm pp
.Nd prepend text to standard input
.Sh SYNOPSIS
.Nm
.Op Ar text ...
.Sh DESCRIPTION
.Nm
is a utility to prepend text to each line of standard input.
The text to prepend standard input with is given via command line arguments in a
similar fashion to the
.Xr echo 1
utility.
.Sh EXAMPLES
Print the contents of
.Ar file1
to the standard output with each line prefixed with the string
.Sq "[LOG] ":
.Pp
.Dl $ pp '[LOG] ' <file1
.Sh SEE ALSO
.Xr ap 1 ,
.Xr echo 1
